language: rust
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

sudo: required

# run builds for all the trains (and more)
rust:
  - nightly

env:
  global:
  - secure: EVuqW4VBIt3+mYgUZpHL5S4waHRBZsX1zqBO8wfNnw1n5M8VPi5MqEiyiPbYBJOYJWCJVCf2qwTIjl2L45wf4QaDBxSHIim+HKYnwRNaROOZkmUpFLymS7kGAZV3ujdm70x0QdDqDiLrm0S1+ii59swth7rtd++IRz6gBbKooZdsbV0GJcdr4EU+PpcQAqlM4JlCRqgMl/of5jMsFY7YepVxKqMnq4O+lCIMUCq3lvvu3XLm5dKk6ZhSJuzdQJTfBJKxfo6myz0C44K/Tp4F6x7u+sVumvma5zjXqXf2/1Q+79a8p+9xXuKKytIQBC98pO2a5FxkhZKtglEYlhaQ3qTXv2enKjTj6chHOf08dwDoEGw2eWfGvDm1dnKV39Gk5HyBuMRzYg9flvFReedwlGxZNOe7xToIOgizTy2S/zPu4bROJwlA3etLSVuBMpRcMztUALAKMdOXiNxc4WyuLQ7rhjmzHLIKq846vJBTQlov0AQYQhvoM6SAGiYi/sepUZrOOy7pnddE87m4AsEnNUokP8dssA/Jtqv8fCUqnM83oEir6k+pRMrcrRo1QL7kHHnZjb1dyjj/cRjzzZxYzzMsYgNcbRxW7yEp7Pp8CEdGqlfKAJL4uvjcIOcQfm19WIHNtcaHF1BrLCLHQ9YRT8Hx7wwdMTViFblAOBioPrs=
  # override the default `--features unstable` used for the nightly branch (optional)
  - TRAVIS_CARGO_NIGHTLY_FEATURE="date engine random"
  - R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH
  - BOOTSTRAP_LATEX="1" BOOTSTRAP_PANDOC="1" PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install libfreetype6 libfreetype6-dev
  - sudo apt-get install libfontconfig1 libfontconfig1-dev
  - sudo apt-get install texlive-xelatex

install:
  - ./travis-tool.sh install_r_binary Rcpp RCurl stringi plyr dplyr 
  - ./travis-tool.sh install_r htmltools knitr miniUI rmarkdown yaml servr rsconnect htmlwidgets webshot
  - ./travis-tool.sh install_github rstudio/bookdown
  - ./travis-tool.sh install_github rustr/rustinr
  - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
  - sudo tar xvjf $PHANTOM_JS.tar.bz2
  - sudo mv $PHANTOM_JS /usr/local/share
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin

script: 
  - cd "$TRAVIS_BUILD_DIR"
  - Rscript _render.R
  - # This generates a `web` directory containing the website.
  - cp ./CNAME ./_book/CNAME
  - cd _book
  - git init
  - git checkout -b gh-pages
  - git add .
  - git -c user.name='travis' -c user.email='travis@travis.travis' commit -m init
  - # Make sure to make the output quiet, or else the API token will leak!
  - # This works because the API key can replace your password.
  - git push --force --quiet "https://qinwf:$GITHUB_API_KEY@github.com/rustr/book.git" gh-pages > /dev/null 2>&1

notifications:
  email:
    on_success: change
    on_failure: always
